---
abstract: 'To dig CPAN'
author:
  - 'Gabor Szabo'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Deep: 0.108
  Test::More: 0.98
  Test::NoWarnings: 1.02
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Digger
no_index:
  directory:
    - eg
    - inc
    - share
    - t
requires:
  Archive::Any: 0.0932
  Archive::Tar: 1.76
  Archive::Zip: 1.30
  Capture::Tiny: 0.10
  Carp: 0
  Cwd: 0
  DBD::SQLite: 1.35
  DBI: 1.611
  Dancer: 1.3040
  Data::Dumper: 0
  Encode: 2.38
  File::Basename: 0
  File::Copy: 0
  File::Copy::Recursive: 0.38
  File::Find::Rule: 0.32
  File::Path: 0
  File::ShareDir: 1.03
  File::Spec: 0
  File::Temp: 0
  Getopt::Long: 0
  JSON: 2.51
  JSON::XS: 2.3
  List::Util: 0
  Moose: 2.0006
  MooseX::StrictConstructor: 0.16
  POSIX: 0
  PPI::Document: 0
  PPI::Find: 1.215
  PPIx::EditorTools: 0.12
  Parse::CPAN::Packages: 2.33
  Parse::CPAN::Whois: 0.02
  Perl::Critic: 1.106
  Perl::MinimumVersion: 1.28
  Plack: 0.9978
  Plack::Handler::FCGI: 0
  Plack::Runner: 0
  Plack::Util: 0
  Pod::Simple: 3.16
  Pod::Simple::HTML: 0
  Template: 2.22
  Time::HiRes: 0
  YAML: 0.73
  autodie: 2.10
  perl: 5.008008
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
